	version: '2'
 
	services:
	    nginx-proxy:
	        image: jwilder/nginx-proxy
	 
	        ports:
	         - "80:80"
	         - "443:443"
	        volumes:
	          - /var/run/docker.sock:/tmp/docker.sock:ro
	          - ./certs:/etc/nginx/certs:ro
	          - ./vhostd:/etc/nginx/vhost.d
	          - ./html:/usr/share/nginx/html
	        labels:
	          - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
	    letsencrypt:
	#        image: jrcs/letsencrypt-nginx-proxy-companion
	        image: jrcs/letsencrypt-nginx-proxy-companion:v1.13
	        restart: always
	        environment:
	        - NGINX_PROXY_CONTAINER=nginx-proxy
	#        - DEFAULT_EMAIL=example@gmail.com
	        volumes:
	          - ./certs:/etc/nginx/certs:rw
	          - ./vhostd:/etc/nginx/vhost.d
	          - ./html:/usr/share/nginx/html
	          - /var/run/docker.sock:/var/run/docker.sock:ro
	    wordpress:
	        image: wordpress
	        container_name: wordpress_1
	        links:
	         - mariadb:mysql
	         - redis
	        expose:
	         - 80
	        environment:
	         - WORDPRESS_DB_PASSWORD=qwertyqwerty
	         - WORDPRESS_DB_USER=userwp
	         - WORDPRESS_DB_NAME=wpdb
	         - WP_REDIS_HOST="redis"
	         - "VIRTUAL_HOST=prueba.local"
	         - "LETSENCRYPT_HOST=prueba.local"
	         - "LETSENCRYPT_EMAIL=example@gmail.com"
	        volumes:
	         - ./html:/var/www/html
	    wordpress2:
	        image: wordpress
	        container_name: wordpress_2
	        links:
	         - mariadb:mysql
	         - redis
	        expose:
	         - 80
	        environment:
	         - WORDPRESS_DB_PASSWORD=qwertyqwerty
	         - WORDPRESS_DB_USER=userwp
	         - WORDPRESS_DB_NAME=wpdb
	         - WP_REDIS_HOST="redis"
	         - "VIRTUAL_HOST=prueba.local"
	         - "LETSENCRYPT_HOST=prueba.local"
	         - "LETSENCRYPT_EMAIL=example@gmail.com"
        volumes:
	         - ./html:/var/www/html
	    wordpress3:
	        image: wordpress
	        container_name: wordpress_3
	        links:
	         - mariadb:mysql
	         - redis
	        expose:
	         - 80
	        environment:
	         - WORDPRESS_DB_PASSWORD=qwertyqwerty
	         - WORDPRESS_DB_USER=userwp
	         - WORDPRESS_DB_NAME=wpdb
	         - WP_REDIS_HOST="redis"
	         - "VIRTUAL_HOST=prueba.local"
	         - "LETSENCRYPT_HOST=prueba.local"
	         - "LETSENCRYPT_EMAIL=example@gmail.com"
	        volumes:
	         - ./html:/var/www/html
	    wordpress4:
	        image: wordpress
	        container_name: wordpress_4
	        links:
	         - mariadb:mysql
	         - redis
	        expose:
	         - 80
	        environment:
	         - WORDPRESS_DB_PASSWORD=qwertyqwerty
         - WORDPRESS_DB_USER=userwp
	         - WORDPRESS_DB_NAME=wpdb
	         - WP_REDIS_HOST="redis"
	         - "VIRTUAL_HOST=prueba.local"
	         - "LETSENCRYPT_HOST=prueba.local"
	         - "LETSENCRYPT_EMAIL=example@gmail.com"
	        volumes:
	         - ./html:/var/www/html
	    mariadb:
	        image: mariadb
	 
	        environment:
	         - MYSQL_ROOT_PASSWORD=qwerty123456789
	         - MYSQL_DATABASE=wpdb
	         - MYSQL_USER=userwp
	         - MYSQL_PASSWORD=qwertyqwerty
	        volumes:
	         - ./database:/var/lib/mysql
	    redis:
	        image: 'bitnami/redis:latest'
	        environment:
	         - ALLOW_EMPTY_PASSWORD=yes
	   

